spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:  https://gitee.com/jen-yenpin/config_cloud
          username: jen.yenpin@gmail.com
          password: gi3111363
          timeout: 5
          default-label: master

#服务的端口号
server:
  port: 9100


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/